# configuracao do bd
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = topicos1
quarkus.datasource.password = !Bruno1234
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/topicos1db

quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# === JWT CONFIG ===
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.issuer=unitins-jwt
mp.jwt.verify.publickey.location=token/publicKey.pem
smallrye.jwt.sign.key.location=token/privateKey.pem

# Habilita CORS
quarkus.http.cors.enabled=true

# Origem permitida
quarkus.http.cors.origins=http://localhost:4200

# Métodos HTTP permitidos
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Cabeçalhos permitidos
quarkus.http.cors.access-control-allow-headers=Authorization,Content-Type

# Expor cabeçalhos para o browser
quarkus.http.cors.exposed-headers=Authorization

# Permitir credenciais
quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.static-resources.locations=uploads

quarkus.http.static-resources.enable=true

# MinIO (S3-compatible)
app.s3.endpoint=http://minio:9000
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=minioadmin
quarkus.s3.aws.credentials.static-provider.secret-access-key=minioadmin

# Nome do bucket a usar
app.s3.bucket=controles